# Projecte Lluc - Dani | 24/03/2026 - 2n ASIX | Versió 1

# Configuració del API Gateway NGINX
# 
# Aquest arxiu configura un servidor proxy invers que:
# 1. Redirigeix totes les peticions HTTP a HTTPS per seguretat (Igual que hem fet algun cop amb Apache)
# 2. Gestiona certificats SSL/TLS per a connexions encriptades amb els certificats generats del Dockerfile
# 3. Enruta les peticions a diferents serveis (frontend, products, orders, users)

events {}
http {
    # Establir la codificació de caràcters per a totes les respostes
    # Això ens ajuda a poder controlar correctament els accents i els caràcters especials.
    # Sense aquesta part no els mostra correctament.
    charset utf-8;

    # Servidor HTTP - Redirigir totes les peticions a HTTPS
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }

    # Servidor HTTPS - Proxy invers amb certificat encriptat.
    server {
        listen 443 ssl;
        server_name _;

        # Rutes certificats SSL/TLS per HTTPS.
        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        # Configuració de protocols SSL/TLS segurs
        ssl_protocols TLSv1.2 TLSv1.3;
        # Utilitzar xifratge fort i desactivar els débils
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Enrutament de peticions a cada servei

        # Ruta arrel - Serveix el frontend estàtic
        location / { proxy_pass http://frontend:80; }
        # Ruta API de productes
        location /api/products { proxy_pass http://product-service:5001/products; }
        # Ruta API de comandes
        location /api/orders { proxy_pass http://order-service:5002/orders; }
        # Ruta API d'usuaris
        location /api/users { proxy_pass http://user-service:5003/users; }
    }
}
