apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose_v2.yml --namespace shopmicro3
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
  namespace: shopmicro3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose_v2.yml --namespace shopmicro3
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - image: lsanchez5420/shopmicro-api-gateway:v1
          name: api-gateway
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/nginx
              name: nginx-logs
      restartPolicy: Always
      volumes:
        - name: nginx-logs
          persistentVolumeClaim:
            claimName: nginx-logs
