apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose_v2.yml --namespace shopmicro3
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
  namespace: shopmicro3
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: api-gateway
