apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose_v2.yml --namespace shopmicro3
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: notification-service
  name: notification-service
  namespace: shopmicro3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notification-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose_v2.yml --namespace shopmicro3
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: notification-service
    spec:
      containers:
        - env:
            - name: RMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: RMQ_HOST
          image: lsanchez5420/shopmicro-notification-service:v1
          name: notification-service
      restartPolicy: Always
