apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose_v2.yml --namespace shopmicro3
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: order-service
  name: order-service
  namespace: shopmicro3
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: order-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose_v2.yml --namespace shopmicro3
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: order-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shop-db-secret
                  key: MYSQL_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: REDIS_HOST
            - name: RMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: RMQ_HOST
          image: lsanchez5420/shopmicro-order-service:v2
          name: order-service
      restartPolicy: Always
