apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: shopmicro3
data:
  DB_HOST: "shop-db.shopmicro3.svc.cluster.local"
  DB_NAME: "shop_db"
  DB_USER: "shopmicro-adm"
  REDIS_HOST: "cache.shopmicro3.svc.cluster.local"
  RMQ_HOST: "message-queue.shopmicro3.svc.cluster.local"