apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: shop-db-claim1
  name: shop-db-claim1
  namespace: shopmicro3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
